### ISSUE TITLE
Open when the component load

### ISSUE THREAD

**Issue by rodboc** [asotog/squeezebox#1]
Hi Mate, How can you keep open the component when it is load? I mean when the component load instead of showing the item collapsed, show them items open.

Thanks

**Comment by asotog** [comment]
hi, actually it has to be code a change if you see https://github.com/asotog/squeezebox/blob/master/components/sb-item.ts#L17  the flag is not an input we'll be updating this in the next couple of days i think, thanks for the feedback

**Comment by asotog** [comment]
Featured added please check docs now https://www.npmjs.com/package/squeezebox#options and update to 1.0.8
