### ISSUE TITLE
Cannot change the plus icon.

### ISSUE THREAD

**Issue by tanmoycsit** [asotog/squeezebox#10]
I want to change the + icon into > and cross icon into down arrow. How can i do this?

**Comment by asotog** [comment]
Hi @tanmoycsit  via css, it depends how you want to do this, for example lets say you want to use a png or svg for the icon, first you need to remove the default styles:

```
.squeezebox .sb-item-head a .toggle-icon:before,
.squeezebox .sb-item-head a .toggle-icon:after {
    display: none;
}
```

and use your icon:
```
.squeezebox .sb-item-head a .toggle-icon {
    background-image: url( . . . );
    background-size: . . . .;
    ...
}
```

**Comment by tanmoycsit** [comment]
Hello @asotog 
before your suggestion i found a temporary solution like 
```
.squeezebox .sb-item-head a .toggle-icon:before {
border: solid black;
    border-width: 0 3px 3px 0;
    display: inline-block;
    padding: 4px;
     transform: rotate(-45deg);
    -webkit-transform: rotate(-45deg);
}
```

But your result is better then min. :) 
thanks for help.
