### ISSUE TITLE
Refresh item size

### ISSUE THREAD

**Issue by HugoHeneault** [asotog/squeezebox#12]
My sbItemBody height will change sometimes and I'd like to refresh it. 

I can't find a way to achieve it without closing/opening again by toggling.

How would you do it?

**Comment by asotog** [comment]
This seems like a bug, will check that later today or tomorrow,  div is keeping the height after animation, it should use default/auto height css instead after animation completed

**Comment by HugoHeneault** [comment]
The height stays in the style, si it's probably a bug.

**Comment by asotog** [comment]
@HugoHeneault please check out latest 1.1.13 for this, feel free to open again
