### ISSUE TITLE
Open first item by default

### ISSUE THREAD

**Issue by shubhamsinghal** [asotog/squeezebox#16]
Using loop for adding items, I am not able to let first item open first time when application loads.

**Comment by asotog** [comment]
Hi there,
Well you can do something like this:
```
<sb-item  *ngFor="let item of itemsList; let first = first;" [collapsed]="!first">
...
```
thanks,

**Comment by shubhamsinghal** [comment]
Thank you for the solution!!
It working as expected.

Regards

**Comment by shubhamsinghal** [comment]
What if two squeeze boxes are there in same screen. 
I am using tab and both tab have squeezebox. I applied same solution for both but first tab is working fine
in second tab its working like this-
Collapsed class is not applying in first item of second tab but body is not showing (sb-item-body has still height: 0)

**Comment by asotog** [comment]
mm i think because second tab is hidden so there is no way to get proper height values will try to reproduce, i guess we can move this to other ticket

**Comment by shubhamsinghal** [comment]
Ok

**Comment by asotog** [comment]
second bug described moved to https://github.com/asotog/squeezebox/issues/17
