### ISSUE TITLE
First item is not opening in second squeezebox if two squeezebox are there in same screen.

### ISSUE THREAD

**Issue by shubhamsinghal** [asotog/squeezebox#17]
I am using tab and both tab have squeezebox.
Using this solution
<sb-item  *ngFor="let item of itemsList; let first = first;" [collapsed]="!first">
for both squeezeboxes, I applied same solution- first squeezebox of tab1 is working fine but second squeeze box in tab2 its working like this-
Collapsed class is not applying in first item of second tab but body is not showing (sb-item-body has still height: 0)

**Comment by shubhamsinghal** [comment]
@asotog Would you find any solution?

**Comment by asotog** [comment]
will take a look further, i think for now, you can try to set again the items list once tab becomes active/inactive, this is similar to this https://github.com/jtblin/angular-chart.js/issues/29, by setting again, it should re render again the component

**Comment by asotog** [comment]
another approach i'm thinking is to provide a refresh method so you can call while tab getting active/inactive

**Comment by asotog** [comment]
can you please check latest version and check this new method https://github.com/asotog/squeezebox#methods

**Comment by asotog** [comment]
closing it because of no response, pls reopen if problem raises again
