### ISSUE TITLE
Unable to load transpiler to transpile

### ISSUE THREAD

**Issue by avoliva** [asotog/squeezebox#3]
Any idea how to solve this? I get this in the console when I install the package and include it in my SystemJS config.

**Comment by asotog** [comment]
are you able to replicate it with plunkr ? which angular version you using ? can you paste more config details here ?

**Comment by avoliva** [comment]
Latest version of angular 2
Basically my config looks like the one in the demo plunkr but without these lines:

```
 // DEMO ONLY! REAL CODE SHOULD NOT TRANSPILE IN THE BROWSER
    transpiler: 'ts',
    typescriptOptions: {
      tsconfig: true
    },
    meta: {
      'typescript': {
        "exports": "ts"
      }
    },
```
Here's an example: http://plnkr.co/edit/fzerwM4sd1y26sQ0LSXh?p=preview

Still getting the hang of angular and typescript so I'm not sure how to proceed. It seems we don't want it being transpiled in the browser, but it needs to be transpiled at some point.

**Comment by avoliva** [comment]
Any idea?

**Comment by asotog** [comment]
From your plunkr, systemjs.config.js was missing 
```
transpiler: 'ts',
    typescriptOptions: {
      tsconfig: true
    },
    meta: {
      'typescript': {
        "exports": "ts"
      }
    },
```
and squeezebox default extension was missing `js` instead of `ts`
