### ISSUE TITLE
Is there any Reason to leave the empty href in the <a> Tag?

### ISSUE THREAD

**Issue by SpecialNick** [asotog/squeezebox#4]
Hello, 

I was wondering if it was of any use to keep the "href="#"' attribute in the <a> tag for the sbItemHead. 

I personally would enjoy it if you would remove it because all it does is add the link you are clicking in the corner:

![image](https://cloud.githubusercontent.com/assets/22095497/21540015/7342916a-cdac-11e6-97aa-6a30e22adcc8.png)

Maybe you could even add a CSS-Class for even easier styling?

**Comment by SpecialNick** [comment]
@asotog ?

**Comment by asotog** [comment]
Yeah i think that might be removed, is not needed

**Comment by asotog** [comment]
wait @SpecialNick  but how are you getting # in the address bar ? i meant the click event has `preventDefault()`, https://github.com/asotog/squeezebox/blob/master/components/sb-item-head.ts#L18

**Comment by SpecialNick** [comment]
I'm not getting the # in the adress bar, it just shows up in the bottom left/right corner when hovering over the sbItemHead 

If you open your example plunker and get it in a pop up window then you can recreate it: 
![unbenannt](https://cloud.githubusercontent.com/assets/22095497/22389048/ff4e9516-e4e3-11e6-99d9-1a3efa8dcc75.png)

to bad you apparently can't see my mouse when I'm taking a screenshot >.< But I am hovering over "Item 1" in above screenshot

**Comment by asotog** [comment]
no worries got it
