### ISSUE TITLE
Error resolving symbol SqueezeBoxModule

### ISSUE THREAD

**Issue by samarism** [asotog/squeezebox#5]
I get the following error when trying to use the component. 

`
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/node_modules/@angular/core/index.d.ts, resolving symbol SqueezeBoxModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/index.ts, resolving symbol SqueezeBoxModule in /Users/samar/projects/sacredangle/node_modules/squeezebox/index.ts`

On installation of the component I got some unmet dependencies errors. Could these be causing the above issue?

<img width="1053" alt="screen shot 2017-02-15 at 8 13 47 am" src="https://cloud.githubusercontent.com/assets/2143346/22958707/feb0a230-f356-11e6-8d5b-1c9d4fd0590c.png">

**Comment by samarism** [comment]
Update:

The above issue was solved by updating the the angular-cli as per guidelines at this [link](https://github.com/angular/angular-cli#updating-angular-cli)

**Comment by asotog** [comment]
thanks so much, i just tried to install the component from a cli project got some issues, so please expect to have a new version soon

**Comment by asotog** [comment]
npm registry updated with latest version 1.1.4, tested from angular cli project, looking fine now, please try again
https://github.com/asotog/squeezebox/commit/8d608a56cd5c5ddb8f7d98535df759362f06edc0
https://github.com/asotog/squeezebox/commit/987768b0be70bb43c6973e33809ef7ba86f581ad

**Comment by samarism** [comment]
Cool, its working fine now. Thanks for sharing this component :)
